spring.application.name=email-service

server.port=8084

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Mail (use your gmail/app password later)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vinayakdeshpande06@gmail.com
spring.mail.password=cacoatutahocofnj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
