spring.application.name=user-service

server.port=8083

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

# Database
spring.datasource.url=jdbc:mysql://mysql:3306/user_db
spring.datasource.username=staynest
spring.datasource.password=Vinayak@28

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
