
# Gateway auto-discovery services registered in Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
 

server.port=8080
spring.application.name=api-gateway

spring.main.web-application-type=reactive

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Explicit Routes
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=auth-service
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=ai-service
spring.cloud.gateway.routes[2].uri=lb://ai-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/ai-service/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1